### ISSUE TITLE
Banshee media player always starts with the volume widget muted

### ISSUE THREAD

**Issue by calexil** [linuxmint/gnome-apps#31]
mint 18 beta, MATE, compton, banshee starts muted(but not actually muted as music is playing at 100%) until volume rocker is adjusted then volume jumps to level indicated.

occurring up to 2.6.3 sarah

When launched from terminal:

http://dpaste.com/3D3B0VR

more info

https://bugzilla.gnome.org/show_bug.cgi?id=757930

**Comment by calexil** [comment]
still happening mint 18 mate

**Comment by calexil** [comment]
anyone seein this?
![screenshot at 2016-11-09 14-48-51](https://cloud.githubusercontent.com/assets/3487071/20152298/ba517cc6-a68b-11e6-9860-a46c8fbd7eec.png)

**Comment by calexil** [comment]
still happening in mate 18.2

**Comment by JosephMcc** [comment]
We no longer ship Banshee and it seems to be pretty much dead.
